words = [
    "antosha",
    "folke",
    "gofumpt",
    "goimports",
    "gopls",
    "hrsh",
    "keybinds",
    "lazypath",
    "lazyrepo",
    "lazyvim",
    "neovim",
    "nvim",
    "protols",
    "pyright",
    "sqlls",
    "staticcheck",
    "stylua",
    "vscode",
]
